### ISSUE TITLE
Typo, x2

### ISSUE THREAD

**Issue by dajare** [standardebooks/charles-dickens_hard-times#2]
In [the long description][a], one of the characters is referred to as "Rachel", but she is consistently named as "Rachael" in the book.

Checking this led to one typo in the text of the novel itself:

- `said Rachel` > `said Rachael` in [ch. 3/5, "Found"][b]
- [page scan][c] for confirmation

[a]: https://github.com/standardebooks/charles-dickens_hard-times/blob/c32cbc128741f0472cb33cba3b332a2097bc8735/src/epub/content.opf#L63
[b]: https://github.com/standardebooks/charles-dickens_hard-times/blob/c32cbc128741f0472cb33cba3b332a2097bc8735/src/epub/text/chapter-3-5.xhtml#L21
[c]: https://archive.org/details/hardtimes1854dick/page/331/mode/1up

**Comment by acabal** [comment]
Thanks! This has been updated locally and the fix should be pushed in the next few days.
